[profile.default]
src = "src/test/uniswap-v3/exercises"
test = "test/uniswap-v3"
libs = ["lib"]
# solc_version = "0.8.24"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 80